# ======= SAME DOCKER IMAGE ===========
image: localhost:5000/spyglass_centos8:latest
# =========== ALL THE STAGES ===========
# All the stages will be executed in this order
stages:
    - linting

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

# =========== STAGE ===========
#   - linting
# =============================
linting_spyglass:
  stage: linting
  artifacts:
    paths:
      #TODO:add spyglass log
      - ./artifact_linting_verilator_BSC.log
    when: always
    expire_in: 30 days
  script:
    - echo "lint_spyglass"
    - make "docker_spyglass"    # This is a fake call inside the Makefile, just and example
  allow_failure: false
