CC=pdflatex

all: spec 

spec: main.tex 1-Section.tex 2-Section.tex 3-Section.tex 4-Section.tex 5-Section.tex
	$(CC) main.tex

clean:
	rm *.aux *.log *.blg *.bbl *.out

clear:
	rm *.aux *.log *.blg *.bbl *.out *.pdf 

